import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/styles/globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { cn } from "@/lib/utils";
import ToastProvider from "@/providers/toast-provider";
import QueryProvider from "@/providers/query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book My Stay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "flex flex-col min-h-screen")}>
        <QueryProvider>
          <Header />
          {children}
          <Footer />
          <ToastProvider />
        </QueryProvider>
      </body>
    </html>
  );
}
